# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\python\taskmanager\taskmanager.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(464, 517)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 30pt \"Times New Roman\";\n"
"background: #e284fa;\n"
"color: white;\n"
"border-radius: 10px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.add_line = QtWidgets.QLineEdit(self.splitter)
        self.add_line.setObjectName("add_line")
        self.add_button = QtWidgets.QPushButton(self.splitter)
        self.add_button.setStyleSheet("font: 11pt \"Times New Roman\";\n"
"background-color: #e284fa;\n"
"color: white;")
        self.add_button.setFlat(False)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_2.addWidget(self.splitter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.task_list = QtWidgets.QListWidget(Form)
        self.task_list.setStyleSheet("font:12pt;")
        self.task_list.setObjectName("task_list")
        self.verticalLayout.addWidget(self.task_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.del_button = QtWidgets.QPushButton(Form)
        self.del_button.setStyleSheet("font: 11pt \"Times New Roman\";\n"
"background-color: #e284fa;\n"
"color: white;")
        self.del_button.setObjectName("del_button")
        self.horizontalLayout.addWidget(self.del_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setStyleSheet("font: 11pt \"Times New Roman\";\n"
"background-color: #e284fa;\n"
"color: white;")
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Task manager"))
        self.add_button.setText(_translate("Form", "Add task"))
        self.del_button.setText(_translate("Form", "Delete complete"))
        self.save_button.setText(_translate("Form", "Save"))
